FROM balenalib/rpi-raspbian:buster 

RUN apt update \
    && apt upgrade \
    && apt install -y git sed wget curl

COPY armv6uname.sh .
RUN mv /bin/uname /bin/uname.orig \
    && mv armv6uname.sh /bin/uname

WORKDIR home

RUN git clone https://github.com/uraimo/buildSwiftOnARM.git
RUN cd buildSwiftOnARM \
    && ./clone.sh

COPY forcearmv6.diff ./swift.diffs/aarch32/

