FROM arm32v7/debian:buster

RUN apt update \
    && apt upgrade \
    && apt install -y git sed wget curl

WORKDIR home

RUN git clone https://github.com/uraimo/buildSwiftOnARM.git
RUN cd buildSwiftOnARM \
    && ./clone.sh
