FROM arm32v7/ubuntu:18.04

RUN apt update \
    && apt upgrade \
    && apt install -y git sed wget curl sudo

WORKDIR home

RUN git clone https://github.com/uraimo/buildSwiftOnARM.git
RUN cd buildSwiftOnARM \
    && ./clone.sh
