FROM arm32v7/debian:stretch

RUN apt update \
    && apt upgrade -y \
    && apt install -y git sed wget curl sudo

WORKDIR home

RUN git clone https://github.com/uraimo/buildSwiftOnARM.git
RUN cd buildSwiftOnARM \
    && ./clone.sh
